// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNaP7wnJcCH9FwhTwzmyq7So_5npIoIc',
    appId: '1:280695079354:web:5ff5e91ceefd3106d4dd83',
    messagingSenderId: '280695079354',
    projectId: 'coursati-f8d75',
    authDomain: 'coursati-f8d75.firebaseapp.com',
    databaseURL: 'https://coursati-f8d75-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coursati-f8d75.appspot.com',
    measurementId: 'G-FPDH6R0LHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbbCLaCxlqv5XMJB8d_Q_EccOX-hd9Rms',
    appId: '1:280695079354:android:0f8a1bbaba470a61d4dd83',
    messagingSenderId: '280695079354',
    projectId: 'coursati-f8d75',
    databaseURL: 'https://coursati-f8d75-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coursati-f8d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuxpw09aZf6-jY6foMpeu8bDRgAJqeO24',
    appId: '1:280695079354:ios:672f605688c93e48d4dd83',
    messagingSenderId: '280695079354',
    projectId: 'coursati-f8d75',
    databaseURL: 'https://coursati-f8d75-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coursati-f8d75.appspot.com',
    iosClientId: '280695079354-4qodj8t3b28aqptb44f2vpdnvp82ltmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuxpw09aZf6-jY6foMpeu8bDRgAJqeO24',
    appId: '1:280695079354:ios:672f605688c93e48d4dd83',
    messagingSenderId: '280695079354',
    projectId: 'coursati-f8d75',
    databaseURL: 'https://coursati-f8d75-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'coursati-f8d75.appspot.com',
    iosClientId: '280695079354-4qodj8t3b28aqptb44f2vpdnvp82ltmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursati',
  );
}
